[ -f /etc/bashrc ] && source /etc/bashrc
[ -f ~/.bash-pfetch ] && source ~/.bash-pfetch
[ -f ~/.bash-aliases ] && source ~/.bash-aliases
[ -f ~/.bash-path ] && source ~/.bash-path
[ -f ~/.bash-prompt ] && source ~/.bash-prompt
[ -f ~/.bash-secrets ] && source ~/.bash-secrets
[ -f ~/.bash-settings ] && source ~/.bash-settings
[ -f ~/.bash-variables ] && source ~/.bash-variables
[ -f ~/.bash-misc ] && source ~/.bash-misc
